version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '11:00'
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: '/packages/stream'
    schedule:
      interval: daily
      time: '11:00'
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: '/packages/web'
    schedule:
      interval: daily
      time: '11:00'
    open-pull-requests-limit: 10
