name: Main
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [12, 14]
    name: Build on Node ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [12, 14]
    name: Test on Node ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run test
